version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - $HOME/go/pkg/mod:/go/pkg/mod
    networks:
      - net_common
    ports:
      - "8090:8090"
    environment:
      - TZ=Asia/Shanghai
    command: sleep infinity

networks:
  net_common:
    external: true
