version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - net_common
    ports:
      - "58090:8090"
    command: sleep infinity

networks:
  net_common:
    external: true
