log:
  logDir: ./.logs/
  mainLog: main-%Y-%m-%d.log
  errorLog: error-%Y-%m-%d.log

mysql:
  host: luvx:53306
  username: root
  password: 1121
  dbname: boot

redis:
  host: redis-16127.c294.ap-northeast-1-2.ec2.cloud.redislabs.com:16127
  username: default
  password: xx
  timeout: 200
  maxActive: 30
  maxIdle: 30

mongodb:
  uri: mongodb+srv://xxx:xxx@cluster0.r8xxd.mongodb.net
  database: boot

server:
  port: ":8090"
  debug: true
